@startuml C3_MS_Consentimientos
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title C3 - Componentes | MS Consentimientos

Container(api, "API Gateway / BFF", "Node.js", "Entrada única")
ContainerDb(pg, "BD Central", "PostgreSQL", "Consentimiento")

Container_Boundary(ms, "MS Consentimientos") {
  Component(ctrl, "ConsentController", "REST", "Aceptar/consultar política")
  Component(svc, "ConsentService", "Service", "Validación de aceptación")
  Component(repo, "ConsentRepository", "Repository", "Persistencia (Prisma)")
}

Rel(api, ctrl, "Invoca", "HTTP")
Rel(ctrl, svc, "Usa", "")
Rel(svc, repo, "Usa", "")
Rel(repo, pg, "Lee/Escribe", "SQL")

@enduml
