@startuml C3_MS_Encuestas
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title C3 - Componentes | MS Encuestas

Container(api, "API Gateway / BFF", "Node.js", "Entrada única")
ContainerDb(pg, "BD Central", "PostgreSQL", "EncuestaSatisfaccion")

Container_Boundary(ms, "MS Encuestas") {
  Component(ctrl, "EncuestasController", "REST", "Registrar encuesta")
  Component(svc, "EncuestasService", "Service", "Reglas: 1..5 y validación")
  Component(repo, "EncuestasRepository", "Repository", "Persistencia (Prisma)")
}

Rel(api, ctrl, "Invoca", "HTTP")
Rel(ctrl, svc, "Usa", "")
Rel(svc, repo, "Usa", "")
Rel(repo, pg, "Lee/Escribe", "SQL")

@enduml
